// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfxrnpnultvwszuceqcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmeHJucG51bHR2d3N6dWNlcWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODU0MDksImV4cCI6MjA2NDk2MTQwOX0.xX7Wm_6x0atOI-Z4fJEfYxu5ZwTc-RZFnjbsTlnxW8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);